### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nobananasforyou** [WolframRhodium/muvsfunc#24]
I was wondering if you'd document (e.g. usage examples) of the functions you've written so that people will know how to use them. Currently, there are many scripts but most of them have little to no documentation or sample usage examples of using said functions. I'd like to learn and I know that this is a tedious request. 

Please let me know.

Thank you.

**Comment by WolframRhodium** [comment]
Hi,

I am sorry for the inconvenience caused by the lack of documentation and examples. 

The reasons behind it is that, currently I write these functions solely based on my personal preferences and use, and I only write documentation, comments and examples to facilitate my current and future understanding and usage. (And also I'm too busy to write a comprehensive guide)

I believe a good way to learn them would be to use them. Comparing them with existing similar functions, replacing functions in other scripts (doom9 and other sites provide vast amount of scripts) with functions here. Then, building knowledge on top of experiences, trying to understand their behaviors, and making modifications on them, and write your own library.

**Comment by nobananasforyou** [comment]
Okay.
